window.TRAINING_PLAN = [
  {
    "date": "2026-06-23",
    "week": "预备周",
    "weekday": "周二",
    "start": "灵活",
    "category": "计划启动",
    "content": "整理训练计划；确认早跑路线、跑鞋、袜子和洗澡换衣时间。",
    "duration": "10-20分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "今天不强求补跑，从周四开始进入节奏。"
  },
  {
    "date": "2026-06-24",
    "week": "预备周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "深蹲、箭步蹲、臀桥、提踵、平板支撑，各2-3组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "轻量做即可，给周四早跑留状态。"
  },
  {
    "date": "2026-06-25",
    "week": "预备周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑5km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "40-45分钟",
    "distance": 5.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "全程能聊天，杭州高温高湿时允许再慢20-40秒/km。"
  },
  {
    "date": "2026-06-26",
    "week": "预备周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-06-27",
    "week": "预备周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑4km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "32-36分钟",
    "distance": 4.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周末轻松跑只负责堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-06-28",
    "week": "预备周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离8km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "64-72分钟",
    "distance": 8.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "第一周末只求顺利完成，走跑结合也可以。"
  },
  {
    "date": "2026-06-29",
    "week": "第1周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补6/28长距离，晚上拉伸10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "今天只恢复，不补跑；给6/30早跑留状态。"
  },
  {
    "date": "2026-06-30",
    "week": "第1周",
    "weekday": "周二",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里必须慢到8'00\"/km以后；跑前动态热身3分钟，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "先练慢住；看到7'30\"以内就主动降速，必要时走30秒。"
  },
  {
    "date": "2026-07-01",
    "week": "第1周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-07-02",
    "week": "第1周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-07-03",
    "week": "第1周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-07-04",
    "week": "第1周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑3km；如果腿沉就改散步20分钟。",
    "duration": "24-30分钟",
    "distance": 3.0,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "周日长距离前一天保持松，不加速。"
  },
  {
    "date": "2026-07-05",
    "week": "第1周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离7-8km；前2km放慢热身，中段稳定，最后1km也不冲。",
    "duration": "56-72分钟",
    "distance": 8.0,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "这是补回长距离习惯，不追配速；跑完应还有余力。"
  },
  {
    "date": "2026-07-06",
    "week": "第2周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-07-07",
    "week": "第2周",
    "weekday": "周二",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里必须慢到8'00\"/km以后；跑前动态热身3分钟，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "先练慢住；看到7'30\"以内就主动降速，必要时走30秒。"
  },
  {
    "date": "2026-07-08",
    "week": "第2周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-07-09",
    "week": "第2周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-07-10",
    "week": "第2周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-07-11",
    "week": "第2周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑4km；放松跑姿，保持能聊天。",
    "duration": "32-36分钟",
    "distance": 4.0,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "只堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-07-12",
    "week": "第2周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离9km；全程轻松，最后2km也不要提速。",
    "duration": "72-82分钟",
    "distance": 9.0,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "如果前一晚睡差或天气闷热，改为7-8km。"
  },
  {
    "date": "2026-07-13",
    "week": "第3周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-07-14",
    "week": "第3周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 轻快跑1分钟x6组，组间慢跑1分钟 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4.0,
    "intensity": "快段7'00\"-7'20\"/km",
    "reminder": "动作轻快但不冲刺；如果前两天疲劳，就改轻松跑3.5km。"
  },
  {
    "date": "2026-07-15",
    "week": "第3周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-07-16",
    "week": "第3周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-07-17",
    "week": "第3周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-07-18",
    "week": "第3周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑4km；轻松收，不加速。",
    "duration": "32-36分钟",
    "distance": 4.0,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "周日长距离前一天保持松。"
  },
  {
    "date": "2026-07-19",
    "week": "第3周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离10-11km；前2km慢热身，中段稳定，最后1km不冲。",
    "duration": "80-95分钟",
    "distance": 10.5,
    "intensity": "7'50\"-8'40\"/km",
    "reminder": "如果心率飘高或体感累，10km即可收。"
  },
  {
    "date": "2026-07-20",
    "week": "第4周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-07-21",
    "week": "第4周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 轻快跑1分钟x6组，组间慢跑1分钟 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4.0,
    "intensity": "快段7'00\"-7'20\"/km",
    "reminder": "动作轻快但不冲刺；如果前两天疲劳，就改轻松跑3.5km。"
  },
  {
    "date": "2026-07-22",
    "week": "第4周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-07-23",
    "week": "第4周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-07-24",
    "week": "第4周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-07-25",
    "week": "第4周",
    "weekday": "周六",
    "start": "灵活",
    "category": "休息",
    "content": "休息或轻松3km；身体紧就只散步20分钟。",
    "duration": "0-30分钟",
    "distance": 0.0,
    "intensity": "无/轻松",
    "reminder": "恢复周周六可完全休息。"
  },
  {
    "date": "2026-07-26",
    "week": "第4周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离8-9km；全程轻松。",
    "duration": "64-80分钟",
    "distance": 9.0,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "恢复周不追距离，跑完有余力就是成功。"
  },
  {
    "date": "2026-07-27",
    "week": "第5周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-07-28",
    "week": "第5周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 轻快跑1分钟x6组，组间慢跑1分钟 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4.0,
    "intensity": "快段7'00\"-7'20\"/km",
    "reminder": "动作轻快但不冲刺；如果前两天疲劳，就改轻松跑3.5km。"
  },
  {
    "date": "2026-07-29",
    "week": "第5周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-07-30",
    "week": "第5周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-07-31",
    "week": "第5周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-08-01",
    "week": "第5周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑5km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "40-45分钟",
    "distance": 5.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周末轻松跑只负责堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-08-02",
    "week": "第5周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离13km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "104-117分钟",
    "distance": 13.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "长距离只求稳定完成；超过75分钟建议带水或电解质。"
  },
  {
    "date": "2026-08-03",
    "week": "第6周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-08-04",
    "week": "第6周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 稳定跑3分钟x4组，组间慢跑90秒 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4.0,
    "intensity": "稳定段7'10\"-7'30\"/km",
    "reminder": "工作日只做短刺激，跑完要能正常上班。"
  },
  {
    "date": "2026-08-05",
    "week": "第6周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-08-06",
    "week": "第6周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-08-07",
    "week": "第6周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-08-08",
    "week": "第6周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑5km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "40-45分钟",
    "distance": 5.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周末轻松跑只负责堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-08-09",
    "week": "第6周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离14km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "112-126分钟",
    "distance": 14.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "长距离只求稳定完成；超过75分钟建议带水或电解质。"
  },
  {
    "date": "2026-08-10",
    "week": "第7周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-08-11",
    "week": "第7周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 稳定跑3分钟x4组，组间慢跑90秒 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4.0,
    "intensity": "稳定段7'10\"-7'30\"/km",
    "reminder": "工作日只做短刺激，跑完要能正常上班。"
  },
  {
    "date": "2026-08-12",
    "week": "第7周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-08-13",
    "week": "第7周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-08-14",
    "week": "第7周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-08-15",
    "week": "第7周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑5km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "40-45分钟",
    "distance": 5.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周末轻松跑只负责堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-08-16",
    "week": "第7周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离15km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "120-135分钟",
    "distance": 15.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "长距离只求稳定完成；超过75分钟建议带水或电解质。"
  },
  {
    "date": "2026-08-17",
    "week": "第8周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-08-18",
    "week": "第8周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 稳定跑3分钟x4组，组间慢跑90秒 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4.0,
    "intensity": "稳定段7'10\"-7'30\"/km",
    "reminder": "工作日只做短刺激，跑完要能正常上班。"
  },
  {
    "date": "2026-08-19",
    "week": "第8周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-08-20",
    "week": "第8周",
    "weekday": "周四",
    "start": "06:10",
    "category": "状态检查",
    "content": "30分钟内：轻松跑20分钟 + 后5分钟略提速 + 慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "前段8'00\"-8'45\"/km，后段7'20\"-7'40\"/km",
    "reminder": "只是状态检查，不是测试。"
  },
  {
    "date": "2026-08-21",
    "week": "第8周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-08-22",
    "week": "第8周",
    "weekday": "周六",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周六休息；如果腿很松，可以散步20分钟。"
  },
  {
    "date": "2026-08-23",
    "week": "第8周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离12km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "96-108分钟",
    "distance": 12.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "恢复周长距离，11-12km均可。"
  },
  {
    "date": "2026-08-24",
    "week": "第9周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-08-25",
    "week": "第9周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 稳定跑3分钟x4组，组间慢跑90秒 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4.0,
    "intensity": "稳定段7'10\"-7'30\"/km",
    "reminder": "工作日只做短刺激，跑完要能正常上班。"
  },
  {
    "date": "2026-08-26",
    "week": "第9周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-08-27",
    "week": "第9周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-08-28",
    "week": "第9周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-08-29",
    "week": "第9周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑5km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "40-45分钟",
    "distance": 5.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周末轻松跑只负责堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-08-30",
    "week": "第9周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离16km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "128-144分钟",
    "distance": 16.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "长距离只求稳定完成；超过75分钟建议带水或电解质。"
  },
  {
    "date": "2026-08-31",
    "week": "第10周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-09-01",
    "week": "第10周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 目标配速3分钟x4组，组间慢跑90秒 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4.0,
    "intensity": "目标段7'00\"-7'10\"/km",
    "reminder": "只练节奏感，不把工作日早上跑成大课。"
  },
  {
    "date": "2026-09-02",
    "week": "第10周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-09-03",
    "week": "第10周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-09-04",
    "week": "第10周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-09-05",
    "week": "第10周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑5km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "40-45分钟",
    "distance": 5.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周末轻松跑只负责堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-09-06",
    "week": "第10周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离17km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "136-153分钟",
    "distance": 17.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "长距离只求稳定完成；超过75分钟建议带水或电解质。"
  },
  {
    "date": "2026-09-07",
    "week": "第11周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-09-08",
    "week": "第11周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 目标配速3分钟x4组，组间慢跑90秒 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4.0,
    "intensity": "目标段7'00\"-7'10\"/km",
    "reminder": "只练节奏感，不把工作日早上跑成大课。"
  },
  {
    "date": "2026-09-09",
    "week": "第11周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-09-10",
    "week": "第11周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-09-11",
    "week": "第11周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-09-12",
    "week": "第11周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑5km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "40-45分钟",
    "distance": 5.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周末轻松跑只负责堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-09-13",
    "week": "第11周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离18km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "144-162分钟",
    "distance": 18.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "长距离只求稳定完成；超过75分钟建议带水或电解质。"
  },
  {
    "date": "2026-09-14",
    "week": "第12周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-09-15",
    "week": "第12周",
    "weekday": "周二",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；保持放松，为周末10km测试留状态。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "测试周不在工作日硬跑。"
  },
  {
    "date": "2026-09-16",
    "week": "第12周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-09-17",
    "week": "第12周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km + 20秒加速跑x3组。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "10km测试移到9/20周日，工作日早上不硬跑。"
  },
  {
    "date": "2026-09-18",
    "week": "第12周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-09-19",
    "week": "第12周",
    "weekday": "周六",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "测试后恢复，周六不安排跑步。"
  },
  {
    "date": "2026-09-20",
    "week": "第12周",
    "weekday": "周日",
    "start": "07:30",
    "category": "10km测试",
    "content": "周末10km测试：慢跑热身1km + 10km尽量均匀跑 + 慢跑冷身1km。",
    "duration": "80-95分钟",
    "distance": 12.0,
    "intensity": "10km均匀；先看1:07-1:09",
    "reminder": "用这次测试判断比赛按A/B/C哪个目标执行。"
  },
  {
    "date": "2026-09-21",
    "week": "第13周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-09-22",
    "week": "第13周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 目标配速3分钟x4组，组间慢跑90秒 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4.0,
    "intensity": "目标段7'00\"-7'10\"/km",
    "reminder": "只练节奏感，不把工作日早上跑成大课。"
  },
  {
    "date": "2026-09-23",
    "week": "第13周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-09-24",
    "week": "第13周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-09-25",
    "week": "第13周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-09-26",
    "week": "第13周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑5km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "40-45分钟",
    "distance": 5.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周末轻松跑只负责堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-09-27",
    "week": "第13周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离18km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "144-162分钟",
    "distance": 18.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "长距离只求稳定完成；超过75分钟建议带水或电解质。"
  },
  {
    "date": "2026-09-28",
    "week": "第14周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-09-29",
    "week": "第14周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 目标配速3分钟x4组，组间慢跑90秒 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4.0,
    "intensity": "目标段7'00\"-7'10\"/km",
    "reminder": "只练节奏感，不把工作日早上跑成大课。"
  },
  {
    "date": "2026-09-30",
    "week": "第14周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-10-01",
    "week": "第14周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-10-02",
    "week": "第14周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-10-03",
    "week": "第14周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑4km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "32-36分钟",
    "distance": 4.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周日长距离较关键，周六保持松。"
  },
  {
    "date": "2026-10-04",
    "week": "第14周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离19km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "152-171分钟",
    "distance": 19.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "最后5km逐步提到A目标配速7'05\"左右；如果热或累，就全程轻松。"
  },
  {
    "date": "2026-10-05",
    "week": "第15周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-10-06",
    "week": "第15周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 目标配速4分钟x3组，组间慢跑2分钟 + 慢跑冷身4分钟。",
    "duration": "28-30分钟",
    "distance": 4.5,
    "intensity": "目标段6'55\"-7'10\"/km",
    "reminder": "专项刺激缩短到30分钟内；周末再承担主要跑量。"
  },
  {
    "date": "2026-10-07",
    "week": "第15周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-10-08",
    "week": "第15周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-10-09",
    "week": "第15周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-10-10",
    "week": "第15周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑4km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "32-36分钟",
    "distance": 4.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周日20km前一天不要加量。"
  },
  {
    "date": "2026-10-11",
    "week": "第15周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离20km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "160-180分钟",
    "distance": 20.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "最后6km可尝试A目标配速；状态很好再靠近B目标配速。"
  },
  {
    "date": "2026-10-12",
    "week": "第16周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-10-13",
    "week": "第16周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 目标配速4分钟x3组，组间慢跑2分钟 + 慢跑冷身4分钟。",
    "duration": "28-30分钟",
    "distance": 4.5,
    "intensity": "目标段6'55\"-7'10\"/km",
    "reminder": "专项刺激缩短到30分钟内；周末再承担主要跑量。"
  },
  {
    "date": "2026-10-14",
    "week": "第16周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-10-15",
    "week": "第16周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-10-16",
    "week": "第16周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-10-17",
    "week": "第16周",
    "weekday": "周六",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "开始减量，周六休息或散步。"
  },
  {
    "date": "2026-10-18",
    "week": "第16周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离16km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "128-144分钟",
    "distance": 16.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "不加速，跑完还有余力即可。"
  },
  {
    "date": "2026-10-19",
    "week": "第17周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-10-20",
    "week": "第17周",
    "weekday": "周二",
    "start": "06:10",
    "category": "赛前唤醒",
    "content": "25-30分钟内：轻松跑3km + 20秒加速跑x4组，组间走或慢跑1分钟。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "轻松为主",
    "reminder": "赛前只唤醒身体，不制造疲劳。"
  },
  {
    "date": "2026-10-21",
    "week": "第17周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-10-22",
    "week": "第17周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "25-30分钟内：轻松跑3km；保持腿感，不加速。",
    "duration": "25-30分钟",
    "distance": 3.0,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "赛前减量，宁可少一点。"
  },
  {
    "date": "2026-10-23",
    "week": "第17周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-10-24",
    "week": "第17周",
    "weekday": "周六",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "比赛前一周，周六不跑或只散步。"
  },
  {
    "date": "2026-10-25",
    "week": "第17周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离12km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "96-108分钟",
    "distance": 12.0,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "赛前最后一次长距离，全程轻松。"
  },
  {
    "date": "2026-10-26",
    "week": "第18周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-10-27",
    "week": "第18周",
    "weekday": "周二",
    "start": "06:10",
    "category": "赛前唤醒",
    "content": "25-30分钟内：轻松跑3km + 20秒加速跑x4组，组间走或慢跑1分钟。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "轻松为主",
    "reminder": "赛前只唤醒身体，不制造疲劳。"
  },
  {
    "date": "2026-10-28",
    "week": "第18周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-10-29",
    "week": "第18周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "25-30分钟内：轻松跑3km；保持腿感，不加速。",
    "duration": "25-30分钟",
    "distance": 3.0,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "赛前减量，宁可少一点。"
  },
  {
    "date": "2026-10-30",
    "week": "第18周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-10-31",
    "week": "第18周",
    "weekday": "周六",
    "start": "灵活",
    "category": "赛前准备",
    "content": "散步或完全休息；整理号码布、芯片、跑鞋、袜子、胶和第二天早餐。",
    "duration": "20-30分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "晚上少折腾，尽量早点睡。"
  },
  {
    "date": "2026-11-01",
    "week": "第18周",
    "weekday": "周日",
    "start": "按赛事通知",
    "category": "杭州半马",
    "content": "杭州半程马拉松比赛；本地参赛，提前出门到起点，前5km保守，5-15km巡航，15km后按状态提速。",
    "duration": "2小时20分-2小时30分",
    "distance": 21.0975,
    "intensity": "稳妥巡航",
    "reminder": "杭州不用出行住宿，但早上留足交通、存包和热身时间；按当天气温补水。"
  },
  {
    "date": "2026-11-02",
    "week": "第19周",
    "weekday": "周一",
    "start": "灵活",
    "category": "赛后恢复",
    "content": "杭州半马赛后完全休息或散步15-20分钟；不跑步，补水、补碳水，观察膝踝小腿反应。",
    "duration": "0-20分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "这是恢复周，不补训练；第二场还在4周后，先把腿养回来。"
  },
  {
    "date": "2026-11-03",
    "week": "第19周",
    "weekday": "周二",
    "start": "灵活",
    "category": "恢复走/拉伸",
    "content": "早上只做散步或拉伸15-20分钟；如果酸痛明显，直接休息。",
    "duration": "15-20分钟",
    "distance": 0.0,
    "intensity": "RPE 2-3",
    "reminder": "不要因为没跑而焦虑，先让肌肉酸痛退掉。"
  },
  {
    "date": "2026-11-04",
    "week": "第19周",
    "weekday": "周三",
    "start": "21:00",
    "category": "灵活力量",
    "content": "20分钟核心+臀腿激活：臀桥、蚌式、提踵、平板，各2组；不做大重量深蹲。",
    "duration": "20分钟",
    "distance": 0.0,
    "intensity": "RPE 4",
    "reminder": "只激活，不练到酸。"
  },
  {
    "date": "2026-11-05",
    "week": "第19周",
    "weekday": "周四",
    "start": "06:10",
    "category": "恢复跑",
    "content": "25分钟内：恢复慢跑2-3km；如果仍明显酸痛，改快走20分钟。",
    "duration": "20-25分钟",
    "distance": 2.5,
    "intensity": "8'30\"-9'20\"/km",
    "reminder": "第一跑只看轻松度，跑完应该更舒服。"
  },
  {
    "date": "2026-11-06",
    "week": "第19周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；泡沫轴轻放松小腿、股四头和臀部。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "继续恢复，不补跑。"
  },
  {
    "date": "2026-11-07",
    "week": "第19周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑4km；全程能聊天，跑后拉伸小腿和臀部。",
    "duration": "32-38分钟",
    "distance": 4.0,
    "intensity": "8'00\"-9'00\"/km",
    "reminder": "如果杭州赛后腿沉，降到3km也可以。"
  },
  {
    "date": "2026-11-08",
    "week": "第19周",
    "weekday": "周日",
    "start": "07:30",
    "category": "恢复长跑",
    "content": "恢复长跑8km；允许走跑结合，最后不加速。",
    "duration": "65-75分钟",
    "distance": 8.0,
    "intensity": "8'00\"-9'00\"/km",
    "reminder": "这不是再冲一次长距离，只是恢复耐力。"
  },
  {
    "date": "2026-11-09",
    "week": "第20周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "杭州赛后一周结束，继续观察疲劳。"
  },
  {
    "date": "2026-11-10",
    "week": "第20周",
    "weekday": "周二",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里压慢，结束后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "工作日仍控制在30分钟内。"
  },
  {
    "date": "2026-11-11",
    "week": "第20周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组。",
    "duration": "20-25分钟",
    "distance": 0.0,
    "intensity": "RPE 5",
    "reminder": "不要练到酸，给周四留腿。"
  },
  {
    "date": "2026-11-12",
    "week": "第20周",
    "weekday": "周四",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：热身10分钟 + 半马配速感4分钟x3组，组间慢跑2分钟 + 放松。",
    "duration": "25-30分钟",
    "distance": 4.0,
    "intensity": "RPE 6-7",
    "reminder": "只找节奏感，不要跑成10km测试。"
  },
  {
    "date": "2026-11-13",
    "week": "第20周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-11-14",
    "week": "第20周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑5km；全程放松，不看配速冲。",
    "duration": "40-45分钟",
    "distance": 5.0,
    "intensity": "7'50\"-8'45\"/km",
    "reminder": "只负责把腿跑顺。"
  },
  {
    "date": "2026-11-15",
    "week": "第20周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离12km；前2km放慢热身，中段稳定，最后1km不冲刺。",
    "duration": "95-110分钟",
    "distance": 12.0,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "漳州前不再堆大疲劳，跑完还能正常走路为准。"
  },
  {
    "date": "2026-11-16",
    "week": "第21周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；晚上拉伸或泡沫轴10分钟。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "这一周是维持专项，不是加量周。"
  },
  {
    "date": "2026-11-17",
    "week": "第21周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：热身10分钟 + 半马配速感5分钟x3组，组间慢跑2分钟 + 放松。",
    "duration": "25-30分钟",
    "distance": 4.5,
    "intensity": "RPE 6-7",
    "reminder": "比上周略稳一点即可，不追最快配速。"
  },
  {
    "date": "2026-11-18",
    "week": "第21周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20分钟轻力量：臀桥、提踵、平板、侧桥，各2组；不做大重量。",
    "duration": "20分钟",
    "distance": 0.0,
    "intensity": "RPE 4-5",
    "reminder": "从这周开始力量只保状态。"
  },
  {
    "date": "2026-11-19",
    "week": "第21周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；保持呼吸轻松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "腿沉就直接降到3km。"
  },
  {
    "date": "2026-11-20",
    "week": "第21周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "给周末最后一次中等长距离留状态。"
  },
  {
    "date": "2026-11-21",
    "week": "第21周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑5km；跑姿放松，结束后拉伸。",
    "duration": "40-45分钟",
    "distance": 5.0,
    "intensity": "7'50\"-8'45\"/km",
    "reminder": "不要跑成比赛。"
  },
  {
    "date": "2026-11-22",
    "week": "第21周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离14km；全程稳定轻松，最后3km也不硬顶。",
    "duration": "110-125分钟",
    "distance": 14.0,
    "intensity": "7'45\"-8'40\"/km",
    "reminder": "这是漳州前最后一次中等长距离，跑完恢复感比配速重要。"
  },
  {
    "date": "2026-11-23",
    "week": "第22周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；晚上拉伸10分钟。",
    "duration": "0-10分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "进入漳州赛前周，开始减量。"
  },
  {
    "date": "2026-11-24",
    "week": "第22周",
    "weekday": "周二",
    "start": "06:10",
    "category": "赛前唤醒",
    "content": "25-30分钟内：轻松跑3km + 20秒加速跑x4组，组间走或慢跑1分钟。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "轻松为主",
    "reminder": "只唤醒身体，不制造疲劳。"
  },
  {
    "date": "2026-11-25",
    "week": "第22周",
    "weekday": "周三",
    "start": "21:00",
    "category": "轻力量",
    "content": "15-20分钟轻力量和拉伸：臀桥、提踵、平板各2组。",
    "duration": "15-20分钟",
    "distance": 0.0,
    "intensity": "RPE 4",
    "reminder": "只做保养，不做新动作。"
  },
  {
    "date": "2026-11-26",
    "week": "第22周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "25分钟内：轻松跑3km，保持腿感，不加速。",
    "duration": "20-25分钟",
    "distance": 3.0,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "赛前减量，宁可少一点。"
  },
  {
    "date": "2026-11-27",
    "week": "第22周",
    "weekday": "周五",
    "start": "按车次",
    "category": "高铁/休息",
    "content": "周五高铁到漳州；不安排跑步。车上每小时起身活动2-3分钟，到达后散步10-15分钟，补水，早点睡。",
    "duration": "0-20分钟",
    "distance": 0.0,
    "intensity": "无",
    "reminder": "今天核心任务是顺利抵达和休息，不补训练。"
  },
  {
    "date": "2026-11-28",
    "week": "第22周",
    "weekday": "周六",
    "start": "灵活",
    "category": "赛前适应",
    "content": "到漳州后赛前适应：轻松慢跑2km或散步20分钟；如旅途疲劳，直接休息。整理参赛物品。",
    "duration": "15-25分钟",
    "distance": 2.0,
    "intensity": "轻松为主",
    "reminder": "能不折腾就不折腾，晚上早点睡。"
  },
  {
    "date": "2026-11-29",
    "week": "第22周",
    "weekday": "周日",
    "start": "按赛事通知",
    "category": "漳州半马",
    "content": "漳州半程马拉松比赛；前5km保守，5-15km稳定巡航，15km后看杭州赛后恢复情况再决定是否提速。",
    "duration": "2小时20分-2小时35分",
    "distance": 21.0975,
    "intensity": "以杭州赛后恢复为准",
    "reminder": "周五已到漳州，比赛日提前到场；若腿沉，优先稳稳完赛。"
  }
];
