window.TRAINING_PLAN = [
  {
    "date": "2026-06-23",
    "week": "预备周",
    "weekday": "周二",
    "start": "灵活",
    "category": "计划启动",
    "content": "整理训练计划；确认早跑路线、跑鞋、袜子和洗澡换衣时间。",
    "duration": "10-20分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "今天不强求补跑，从周四开始进入节奏。"
  },
  {
    "date": "2026-06-24",
    "week": "预备周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "深蹲、箭步蹲、臀桥、提踵、平板支撑，各2-3组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0,
    "intensity": "RPE 5-6",
    "reminder": "轻量做即可，给周四早跑留状态。"
  },
  {
    "date": "2026-06-25",
    "week": "预备周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑5km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "40-45分钟",
    "distance": 5,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "全程能聊天，杭州高温高湿时允许再慢20-40秒/km。"
  },
  {
    "date": "2026-06-26",
    "week": "预备周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-06-27",
    "week": "预备周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑4km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "32-36分钟",
    "distance": 4,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周末轻松跑只负责堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-06-28",
    "week": "预备周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离8km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "64-72分钟",
    "distance": 8,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "第一周末只求顺利完成，走跑结合也可以。"
  },
  {
    "date": "2026-06-29",
    "week": "第1周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补6/28长距离，晚上拉伸10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "今天只恢复，不补跑；给6/30早跑留状态。"
  },
  {
    "date": "2026-06-30",
    "week": "第1周",
    "weekday": "周二",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里必须慢到8'00\"/km以后；跑前动态热身3分钟，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "先练慢住；看到7'30\"以内就主动降速，必要时走30秒。"
  },
  {
    "date": "2026-07-01",
    "week": "第1周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-07-02",
    "week": "第1周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-07-03",
    "week": "第1周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-07-04",
    "week": "第1周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑3km；如果腿沉就改散步20分钟。",
    "duration": "24-30分钟",
    "distance": 3,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "周日长距离前一天保持松，不加速。"
  },
  {
    "date": "2026-07-05",
    "week": "第1周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离7-8km；前2km放慢热身，中段稳定，最后1km也不冲。",
    "duration": "56-72分钟",
    "distance": 8,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "这是补回长距离习惯，不追配速；跑完应还有余力。"
  },
  {
    "date": "2026-07-06",
    "week": "第2周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-07-07",
    "week": "第2周",
    "weekday": "周二",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里必须慢到8'00\"/km以后；跑前动态热身3分钟，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "先练慢住；看到7'30\"以内就主动降速，必要时走30秒。"
  },
  {
    "date": "2026-07-08",
    "week": "第2周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-07-09",
    "week": "第2周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-07-10",
    "week": "第2周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-07-11",
    "week": "第2周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑4km；放松跑姿，保持能聊天。",
    "duration": "32-36分钟",
    "distance": 4,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "只堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-07-12",
    "week": "第2周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离9km；全程轻松，最后2km也不要提速。",
    "duration": "72-82分钟",
    "distance": 9,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "如果前一晚睡差或天气闷热，改为7-8km。"
  },
  {
    "date": "2026-07-13",
    "week": "第3周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-07-14",
    "week": "第3周",
    "weekday": "周二",
    "start": "06:10",
    "category": "恢复跑",
    "content": "30分钟内：先快走3分钟；膝、踝无痛再慢跑3-3.5km，全程能说完整句子。任何疼痛改为快走20分钟。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'20\"-9'10\"/km",
    "reminder": "本周不做快段；跑中或跑后疼痛加重就结束。"
  },
  {
    "date": "2026-07-15",
    "week": "第3周",
    "weekday": "周三",
    "start": "21:00",
    "category": "轻力量",
    "content": "15-20分钟轻力量：臀桥、蚌式开合、鸟狗、平板支撑，各2组；膝踝有痛时不做深蹲、箭步蹲、跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 3-4",
    "reminder": "只做不诱发疼痛的动作；结束后轻柔放松，不练到酸。"
  },
  {
    "date": "2026-07-16",
    "week": "第3周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-07-17",
    "week": "第3周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-07-18",
    "week": "第3周",
    "weekday": "周六",
    "start": "07:30",
    "category": "恢复跑",
    "content": "30分钟内：膝踝无痛时轻松跑3km；有任何不适，改为平路散步20-30分钟。",
    "duration": "25-30分钟",
    "distance": 3,
    "intensity": "8'20\"-9'10\"/km",
    "reminder": "本周末不安排骑行；不以运动量补偿上周。"
  },
  {
    "date": "2026-07-19",
    "week": "第3周",
    "weekday": "周日",
    "start": "07:30",
    "category": "恢复长跑",
    "content": "长距离7km；仅在周二、周四和周六都无痛且体感轻松时，最多8km。前2km慢热身，全程能聊天，最后不加速。",
    "duration": "56-72分钟",
    "distance": 7,
    "intensity": "8'20\"-9'10\"/km",
    "reminder": "膝踝任何不适就改散步或结束；本周不补上周跑量。"
  },
  {
    "date": "2026-07-20",
    "week": "第4周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-07-21",
    "week": "第4周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 轻快跑1分钟x6组，组间慢跑1分钟 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4,
    "intensity": "快段7'00\"-7'20\"/km",
    "reminder": "动作轻快但不冲刺；如果前两天疲劳，就改轻松跑3.5km。"
  },
  {
    "date": "2026-07-22",
    "week": "第4周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-07-23",
    "week": "第4周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-07-24",
    "week": "第4周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-07-25",
    "week": "第4周",
    "weekday": "周六",
    "start": "灵活",
    "category": "休息",
    "content": "休息或轻松3km；身体紧就只散步20分钟。",
    "duration": "0-30分钟",
    "distance": 0,
    "intensity": "无/轻松",
    "reminder": "恢复周周六可完全休息。"
  },
  {
    "date": "2026-07-26",
    "week": "第4周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离8-9km；全程轻松。",
    "duration": "64-80分钟",
    "distance": 9,
    "intensity": "8'00\"-8'50\"/km",
    "reminder": "恢复周不追距离，跑完有余力就是成功。"
  },
  {
    "date": "2026-07-27",
    "week": "第5周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "休息；不补跑，晚上拉伸或泡沫轴10分钟即可。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周一固定恢复，保证后面训练能接住。"
  },
  {
    "date": "2026-07-28",
    "week": "第5周",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "30分钟内：慢跑热身8分钟 + 轻快跑1分钟x6组，组间慢跑1分钟 + 慢跑冷身5分钟。",
    "duration": "28-30分钟",
    "distance": 4,
    "intensity": "快段7'00\"-7'20\"/km",
    "reminder": "动作轻快但不冲刺；如果前两天疲劳，就改轻松跑3.5km。"
  },
  {
    "date": "2026-07-29",
    "week": "第5周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "20-25分钟力量：深蹲、箭步蹲、臀桥、提踵、平板支撑，各2组；结束后拉伸小腿和臀部。",
    "duration": "20-25分钟",
    "distance": 0,
    "intensity": "RPE 5-6",
    "reminder": "控制在30分钟内，不练到酸爆。"
  },
  {
    "date": "2026-07-30",
    "week": "第5周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "30分钟内：轻松跑3-3.5km；第一公里不快于8'00\"/km，跑后慢走放松。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "8'00\"-8'45\"/km",
    "reminder": "工作日轻松跑只负责恢复和打底，别追配速。"
  },
  {
    "date": "2026-07-31",
    "week": "第5周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；如身体紧，可以做小腿、臀部、髋屈肌拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五休息，为周末训练留状态。"
  },
  {
    "date": "2026-08-01",
    "week": "第5周",
    "weekday": "周六",
    "start": "07:30",
    "category": "轻松跑",
    "content": "轻松跑5km；跑前活动脚踝、髋和膝盖3分钟；跑后慢走3分钟。",
    "duration": "40-45分钟",
    "distance": 5,
    "intensity": "7'45\"-8'45\"/km",
    "reminder": "周末轻松跑只负责堆基础，不要跑成比赛。"
  },
  {
    "date": "2026-08-02",
    "week": "第5周",
    "weekday": "周日",
    "start": "07:30",
    "category": "长距离",
    "content": "长距离13km；前2km放慢热身，中段稳定，最后1km也不要硬冲。",
    "duration": "104-117分钟",
    "distance": 13,
    "intensity": "7'35\"-8'30\"/km",
    "reminder": "长距离只求稳定完成；超过75分钟建议带水或电解质。"
  },
  {
    "date": "2026-08-03",
    "week": "第6周·恢复起跑",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-08-04",
    "week": "第6周·恢复起跑",
    "weekday": "周二",
    "start": "06:10",
    "category": "恢复跑",
    "content": "轻松跑4km；先快走3分钟，跑后做单腿平衡和提踵各2组。",
    "duration": "25-30分钟",
    "distance": 4,
    "intensity": "非常轻松，能聊天",
    "reminder": "膝或踝不适加重就改20分钟快走。"
  },
  {
    "date": "2026-08-05",
    "week": "第6周·恢复起跑",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-08-06",
    "week": "第6周·恢复起跑",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑5km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 5,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-08-07",
    "week": "第6周·恢复起跑",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-08-08",
    "week": "第6周·恢复起跑",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行35km，全程能聊天、不冲坡；方案B：LSD 8km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "刚恢复，骑行不超过2小时；任何关节痛都选休息。"
  },
  {
    "date": "2026-08-09",
    "week": "第6周·恢复起跑",
    "weekday": "周日",
    "start": "07:00",
    "category": "周日短长跑",
    "content": "若周六选骑行：今天轻松跑6km；若周六选LSD：今天只跑4km恢复跑，或直接休息。全程能聊天。",
    "duration": "40-75分钟",
    "distance": 6,
    "intensity": "轻松跑，不卡配速",
    "reminder": "周日只比工作日略长，不补跑量。"
  },
  {
    "date": "2026-08-10",
    "week": "第7周·稳定频率",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-08-11",
    "week": "第7周·稳定频率",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "总计25-30分钟：热身10分钟 + 稳定跑2-3分钟x4，组间慢跑90秒-2分钟 + 放松。",
    "duration": "25-30分钟",
    "distance": 4.5,
    "intensity": "稳定段RPE 6-7",
    "reminder": "工作日只找节奏，不追速度。"
  },
  {
    "date": "2026-08-12",
    "week": "第7周·稳定频率",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-08-13",
    "week": "第7周·稳定频率",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑5km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 5,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-08-14",
    "week": "第7周·稳定频率",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-08-15",
    "week": "第7周·稳定频率",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行35km，全程能聊天、不冲坡；方案B：LSD 10km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "优先平路；不做长爬坡和大齿比硬踩。"
  },
  {
    "date": "2026-08-16",
    "week": "第7周·稳定频率",
    "weekday": "周日",
    "start": "07:00",
    "category": "周日短长跑",
    "content": "若周六选骑行：今天轻松跑7km；若周六选LSD：今天只跑4km恢复跑，或直接休息。全程能聊天。",
    "duration": "40-75分钟",
    "distance": 7,
    "intensity": "轻松跑，不卡配速",
    "reminder": "周日只比工作日略长，不补跑量。"
  },
  {
    "date": "2026-08-17",
    "week": "第8周·基础进阶",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-08-18",
    "week": "第8周·基础进阶",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "总计25-30分钟：热身10分钟 + 稳定跑2-3分钟x4，组间慢跑90秒-2分钟 + 放松。",
    "duration": "25-30分钟",
    "distance": 5,
    "intensity": "稳定段RPE 6-7",
    "reminder": "工作日只找节奏，不追速度。"
  },
  {
    "date": "2026-08-19",
    "week": "第8周·基础进阶",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-08-20",
    "week": "第8周·基础进阶",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑5.5km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 5.5,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-08-21",
    "week": "第8周·基础进阶",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-08-22",
    "week": "第8周·基础进阶",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行40km，全程能聊天、不冲坡；方案B：LSD 12km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "LSD超过75分钟带水；骑行不和LSD叠加。"
  },
  {
    "date": "2026-08-23",
    "week": "第8周·基础进阶",
    "weekday": "周日",
    "start": "07:00",
    "category": "周日短长跑",
    "content": "若周六选骑行：今天轻松跑7.5km；若周六选LSD：今天只跑5km恢复跑，或直接休息。全程能聊天。",
    "duration": "40-75分钟",
    "distance": 7.5,
    "intensity": "轻松跑，不卡配速",
    "reminder": "周日只比工作日略长，不补跑量。"
  },
  {
    "date": "2026-08-24",
    "week": "第9周·吸收周",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-08-25",
    "week": "第9周·吸收周",
    "weekday": "周二",
    "start": "06:10",
    "category": "恢复跑",
    "content": "轻松跑4km；先快走3分钟，跑后做单腿平衡和提踵各2组。",
    "duration": "25-30分钟",
    "distance": 4,
    "intensity": "非常轻松，能聊天",
    "reminder": "膝或踝不适加重就改20分钟快走。"
  },
  {
    "date": "2026-08-26",
    "week": "第9周·吸收周",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-08-27",
    "week": "第9周·吸收周",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑5km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 5,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-08-28",
    "week": "第9周·吸收周",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-08-29",
    "week": "第9周·吸收周",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行35km，全程能聊天、不冲坡；方案B：LSD 10km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "保持低负荷，给9月加量做准备。"
  },
  {
    "date": "2026-08-30",
    "week": "第9周·吸收周",
    "weekday": "周日",
    "start": "07:00",
    "category": "周日短长跑",
    "content": "若周六选骑行：今天轻松跑6km；若周六选LSD：今天只跑4km恢复跑，或直接休息。全程能聊天。",
    "duration": "40-75分钟",
    "distance": 6,
    "intensity": "轻松跑，不卡配速",
    "reminder": "周日只比工作日略长，不补跑量。"
  },
  {
    "date": "2026-08-31",
    "week": "第10周·耐力重建",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-09-01",
    "week": "第10周·耐力重建",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "总计25-30分钟：热身10分钟 + 稳定跑2-3分钟x4，组间慢跑90秒-2分钟 + 放松。",
    "duration": "25-30分钟",
    "distance": 5,
    "intensity": "稳定段RPE 6-7",
    "reminder": "工作日只找节奏，不追速度。"
  },
  {
    "date": "2026-09-02",
    "week": "第10周·耐力重建",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-09-03",
    "week": "第10周·耐力重建",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑5.5km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 5.5,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-09-04",
    "week": "第10周·耐力重建",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-09-05",
    "week": "第10周·耐力重建",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行45km，全程能聊天、不冲坡；方案B：LSD 12km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "骑行超过45km时周日绝不加速。"
  },
  {
    "date": "2026-09-06",
    "week": "第10周·耐力重建",
    "weekday": "周日",
    "start": "07:00",
    "category": "周日短长跑",
    "content": "若周六选骑行：今天轻松跑8km；若周六选LSD：今天只跑5km恢复跑，或直接休息。全程能聊天。",
    "duration": "40-75分钟",
    "distance": 8,
    "intensity": "轻松跑，不卡配速",
    "reminder": "周日只比工作日略长，不补跑量。"
  },
  {
    "date": "2026-09-07",
    "week": "第11周·10km前基础",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-09-08",
    "week": "第11周·10km前基础",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "总计25-30分钟：热身10分钟 + 稳定跑4分钟x3，组间慢跑90秒-2分钟 + 放松。",
    "duration": "25-30分钟",
    "distance": 5.5,
    "intensity": "稳定段RPE 6-7",
    "reminder": "工作日只找节奏，不追速度。"
  },
  {
    "date": "2026-09-09",
    "week": "第11周·10km前基础",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-09-10",
    "week": "第11周·10km前基础",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑6km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 6,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-09-11",
    "week": "第11周·10km前基础",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-09-12",
    "week": "第11周·10km前基础",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行45km，全程能聊天、不冲坡；方案B：LSD 14km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "LSD前一晚补水；骑行不和LSD叠加。"
  },
  {
    "date": "2026-09-13",
    "week": "第11周·10km前基础",
    "weekday": "周日",
    "start": "07:00",
    "category": "周日短长跑",
    "content": "若周六选骑行：今天轻松跑8km；若周六选LSD：今天只跑5km恢复跑，或直接休息。全程能聊天。",
    "duration": "40-75分钟",
    "distance": 8,
    "intensity": "轻松跑，不卡配速",
    "reminder": "周日只比工作日略长，不补跑量。"
  },
  {
    "date": "2026-09-14",
    "week": "第12周·10km前最后加量",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-09-15",
    "week": "第12周·10km前最后加量",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "总计25-30分钟：热身10分钟 + 稳定跑4分钟x3，组间慢跑90秒-2分钟 + 放松。",
    "duration": "25-30分钟",
    "distance": 5.5,
    "intensity": "稳定段RPE 6-7",
    "reminder": "工作日只找节奏，不追速度。"
  },
  {
    "date": "2026-09-16",
    "week": "第12周·10km前最后加量",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-09-17",
    "week": "第12周·10km前最后加量",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑6km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 6,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-09-18",
    "week": "第12周·10km前最后加量",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-09-19",
    "week": "第12周·10km前最后加量",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行45km，全程能聊天、不冲坡；方案B：LSD 15km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "最后一次赛前耐力课；LSD只练耐心和补水。"
  },
  {
    "date": "2026-09-20",
    "week": "第12周·10km前最后加量",
    "weekday": "周日",
    "start": "07:00",
    "category": "周日短长跑",
    "content": "若周六选骑行：今天轻松跑8km；若周六选LSD：今天只跑5km恢复跑，或直接休息。全程能聊天。",
    "duration": "40-75分钟",
    "distance": 8,
    "intensity": "轻松跑，不卡配速",
    "reminder": "周日只比工作日略长，不补跑量。"
  },
  {
    "date": "2026-09-21",
    "week": "第13周·苏州10km检验",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-09-22",
    "week": "第13周·苏州10km检验",
    "weekday": "周二",
    "start": "06:10",
    "category": "赛前唤醒",
    "content": "总计25分钟：热身10分钟 + 轻快跑1分钟x4，组间慢跑1分钟 + 放松。",
    "duration": "25-30分钟",
    "distance": 4.5,
    "intensity": "轻快段RPE 6",
    "reminder": "只唤醒，不做疲劳。"
  },
  {
    "date": "2026-09-23",
    "week": "第13周·苏州10km检验",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "只做臀桥、提踵、核心各1-2组，不练酸。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "保持活动，不制造疲劳。"
  },
  {
    "date": "2026-09-24",
    "week": "第13周·苏州10km检验",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑4km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 4,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-09-25",
    "week": "第13周·苏州10km检验",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-09-26",
    "week": "第13周·苏州10km检验",
    "weekday": "周六",
    "start": "灵活",
    "category": "赛前准备",
    "content": "散步15-20分钟或完全休息；不骑行、不LSD。",
    "duration": "0-20分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "腿感新鲜比多跑几公里重要。"
  },
  {
    "date": "2026-09-27",
    "week": "第13周·苏州10km检验",
    "weekday": "周日",
    "start": "按赛事通知",
    "category": "苏州10km测试",
    "content": "B级检验：前3km克制，4-8km保持均匀，最后2km仅在呼吸和腿感稳定时微提速。",
    "duration": "60-75分钟",
    "distance": 10,
    "intensity": "RPE 7，均匀配速",
    "reminder": "目标是检验节奏与心率漂移，不跑成半马模拟或全力PB。"
  },
  {
    "date": "2026-09-28",
    "week": "第14周·10km后恢复",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-09-29",
    "week": "第14周·10km后恢复",
    "weekday": "周二",
    "start": "06:10",
    "category": "恢复跑",
    "content": "轻松跑3.5km；先快走3分钟，跑后做单腿平衡和提踵各2组。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "非常轻松，能聊天",
    "reminder": "膝或踝不适加重就改20分钟快走。"
  },
  {
    "date": "2026-09-30",
    "week": "第14周·10km后恢复",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-10-01",
    "week": "第14周·10km后恢复",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑5km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 5,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-10-02",
    "week": "第14周·10km后恢复",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-10-03",
    "week": "第14周·10km后恢复",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行35km，全程能聊天、不冲坡；方案B：LSD 10km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "苏州后首个周末，选最容易恢复的一项。"
  },
  {
    "date": "2026-10-04",
    "week": "第14周·10km后恢复",
    "weekday": "周日",
    "start": "07:00",
    "category": "周日短长跑",
    "content": "若周六选骑行：今天轻松跑6km；若周六选LSD：今天只跑4km恢复跑，或直接休息。全程能聊天。",
    "duration": "40-75分钟",
    "distance": 6,
    "intensity": "轻松跑，不卡配速",
    "reminder": "周日只比工作日略长，不补跑量。"
  },
  {
    "date": "2026-10-05",
    "week": "第15周·半马专项累积",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-10-06",
    "week": "第15周·半马专项累积",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "总计25-30分钟：热身10分钟 + 稳定跑4分钟x3，组间慢跑90秒-2分钟 + 放松。",
    "duration": "25-30分钟",
    "distance": 5.5,
    "intensity": "稳定段RPE 6-7",
    "reminder": "工作日只找节奏，不追速度。"
  },
  {
    "date": "2026-10-07",
    "week": "第15周·半马专项累积",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-10-08",
    "week": "第15周·半马专项累积",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑6km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 6,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-10-09",
    "week": "第15周·半马专项累积",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-10-10",
    "week": "第15周·半马专项累积",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行45km，全程能聊天、不冲坡；方案B：LSD 15km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "LSD可带水；骑行保持平路低强度。"
  },
  {
    "date": "2026-10-11",
    "week": "第15周·半马专项累积",
    "weekday": "周日",
    "start": "07:00",
    "category": "周日短长跑",
    "content": "若周六选骑行：今天轻松跑8km；若周六选LSD：今天只跑5km恢复跑，或直接休息。全程能聊天。",
    "duration": "40-75分钟",
    "distance": 8,
    "intensity": "轻松跑，不卡配速",
    "reminder": "周日只比工作日略长，不补跑量。"
  },
  {
    "date": "2026-10-12",
    "week": "第16周·西安备用模拟",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-10-13",
    "week": "第16周·西安备用模拟",
    "weekday": "周二",
    "start": "06:10",
    "category": "恢复跑",
    "content": "轻松跑4.5km；先快走3分钟，跑后做单腿平衡和提踵各2组。",
    "duration": "25-30分钟",
    "distance": 4.5,
    "intensity": "非常轻松，能聊天",
    "reminder": "膝或踝不适加重就改20分钟快走。"
  },
  {
    "date": "2026-10-14",
    "week": "第16周·西安备用模拟",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "只做核心、臀桥和提踵激活，不做大重量。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "无痛活动即可。"
  },
  {
    "date": "2026-10-15",
    "week": "第16周·西安备用模拟",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑4km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 4,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-10-16",
    "week": "第16周·西安备用模拟",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "若去西安则整理出行；不额外骑行或加跑。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "西安和桐庐不能都跑半马模拟。"
  },
  {
    "date": "2026-10-17",
    "week": "第16周·西安备用模拟",
    "weekday": "周六",
    "start": "灵活",
    "category": "赛前准备",
    "content": "若参赛则散步15分钟；若不去西安则完全休息，为下周桐庐选择留余地。",
    "duration": "0-20分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不加练。"
  },
  {
    "date": "2026-10-18",
    "week": "第16周·西安备用模拟",
    "weekday": "周日",
    "start": "按赛事通知",
    "category": "西安半马备用模拟",
    "content": "仅在桐庐未中签、且你决定参赛时执行：前16-18km按RPE 6稳定跑，宁可在18km收工；若不参赛则改LSD 16km。",
    "duration": "2小时10分内",
    "distance": 18,
    "intensity": "RPE 6，绝不冲PB",
    "reminder": "这是备用训练赛，不是漳州前的第二个目标。"
  },
  {
    "date": "2026-10-19",
    "week": "第17周·桐庐优先模拟",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-10-20",
    "week": "第17周·桐庐优先模拟",
    "weekday": "周二",
    "start": "06:10",
    "category": "恢复跑",
    "content": "轻松跑3.5km；先快走3分钟，跑后做单腿平衡和提踵各2组。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "非常轻松，能聊天",
    "reminder": "膝或踝不适加重就改20分钟快走。"
  },
  {
    "date": "2026-10-21",
    "week": "第17周·桐庐优先模拟",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "只做轻激活，不练酸。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "腿沉则只拉伸。"
  },
  {
    "date": "2026-10-22",
    "week": "第17周·桐庐优先模拟",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑4km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 4,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-10-23",
    "week": "第17周·桐庐优先模拟",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；若西安已参赛则本周末不增加训练。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "两场半马只选一场。"
  },
  {
    "date": "2026-10-24",
    "week": "第17周·桐庐优先模拟",
    "weekday": "周六",
    "start": "灵活",
    "category": "赛前准备",
    "content": "仅在未跑西安且参加桐庐时散步15分钟；若西安已跑则完全休息。",
    "duration": "0-20分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "两场半马只选一场。"
  },
  {
    "date": "2026-10-25",
    "week": "第17周·桐庐优先模拟",
    "weekday": "周日",
    "start": "按赛事通知",
    "category": "桐庐半马优先模拟",
    "content": "若中签且西安未参赛：前16-18km按RPE 6完成，练配速、补给、鞋袜；若西安已参赛则不出战，改5km恢复跑。",
    "duration": "2小时10分内",
    "distance": 18,
    "intensity": "RPE 6，控制完成",
    "reminder": "桐庐是优先模拟，但不是PB赛；确保三周后漳州还能有新鲜双腿。"
  },
  {
    "date": "2026-10-26",
    "week": "第18周·模拟赛后恢复",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-10-27",
    "week": "第18周·模拟赛后恢复",
    "weekday": "周二",
    "start": "06:10",
    "category": "恢复跑",
    "content": "轻松跑3.5km；先快走3分钟，跑后做单腿平衡和提踵各2组。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "非常轻松，能聊天",
    "reminder": "膝或踝不适加重就改20分钟快走。"
  },
  {
    "date": "2026-10-28",
    "week": "第18周·模拟赛后恢复",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-10-29",
    "week": "第18周·模拟赛后恢复",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑5km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 5,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-10-30",
    "week": "第18周·模拟赛后恢复",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-10-31",
    "week": "第18周·模拟赛后恢复",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行30km，全程能聊天、不冲坡；方案B：LSD 8km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "半马模拟后一周只恢复；骑行和LSD都不能硬顶。"
  },
  {
    "date": "2026-11-01",
    "week": "第18周·模拟赛后恢复",
    "weekday": "周日",
    "start": "07:00",
    "category": "周日短长跑",
    "content": "若周六选骑行：今天轻松跑6km；若周六选LSD：今天只跑4km恢复跑，或直接休息。全程能聊天。",
    "duration": "40-75分钟",
    "distance": 6,
    "intensity": "轻松跑，不卡配速",
    "reminder": "周日只比工作日略长，不补跑量。"
  },
  {
    "date": "2026-11-02",
    "week": "第19周·漳州前减量",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-11-03",
    "week": "第19周·漳州前减量",
    "weekday": "周二",
    "start": "06:10",
    "category": "短质量课",
    "content": "总计25-30分钟：热身10分钟 + 稳定跑4分钟x3，组间慢跑90秒-2分钟 + 放松。",
    "duration": "25-30分钟",
    "distance": 5,
    "intensity": "稳定段RPE 6-7",
    "reminder": "工作日只找节奏，不追速度。"
  },
  {
    "date": "2026-11-04",
    "week": "第19周·漳州前减量",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-11-05",
    "week": "第19周·漳州前减量",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑5km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 5,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-11-06",
    "week": "第19周·漳州前减量",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-11-07",
    "week": "第19周·漳州前减量",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行30km，全程能聊天、不冲坡；方案B：LSD 12km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "最后一次较长耐力课；LSD不超过12km。"
  },
  {
    "date": "2026-11-08",
    "week": "第19周·漳州前减量",
    "weekday": "周日",
    "start": "07:00",
    "category": "周日短长跑",
    "content": "若周六选骑行：今天轻松跑7km；若周六选LSD：今天只跑4km恢复跑，或直接休息。全程能聊天。",
    "duration": "40-75分钟",
    "distance": 7,
    "intensity": "轻松跑，不卡配速",
    "reminder": "周日只比工作日略长，不补跑量。"
  },
  {
    "date": "2026-11-09",
    "week": "第20周·漳州A目标",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-11-10",
    "week": "第20周·漳州A目标",
    "weekday": "周二",
    "start": "06:10",
    "category": "恢复跑",
    "content": "轻松跑4.5km；先快走3分钟，跑后做单腿平衡和提踵各2组。",
    "duration": "25-30分钟",
    "distance": 4.5,
    "intensity": "非常轻松，能聊天",
    "reminder": "膝或踝不适加重就改20分钟快走。"
  },
  {
    "date": "2026-11-11",
    "week": "第20周·漳州A目标",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "只做臀桥、提踵和核心激活各1组；无痛为前提。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "不制造酸痛。"
  },
  {
    "date": "2026-11-12",
    "week": "第20周·漳州A目标",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑3.5km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 3.5,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-11-13",
    "week": "第20周·漳州A目标",
    "weekday": "周五",
    "start": "按车次",
    "category": "高铁出行",
    "content": "周五高铁到漳州；不跑步。车上每小时起身活动2-3分钟，到达后散步10-15分钟，补水、早点睡。",
    "duration": "0-20分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "出行日不加练，腿部放松比步数重要。"
  },
  {
    "date": "2026-11-14",
    "week": "第20周·漳州A目标",
    "weekday": "周六",
    "start": "灵活",
    "category": "赛前适应",
    "content": "轻松慢跑2km或散步20分钟；整理参赛物品和补给。",
    "duration": "15-20分钟",
    "distance": 2,
    "intensity": "非常轻松",
    "reminder": "旅途疲劳就散步或休息，绝不硬跑。"
  },
  {
    "date": "2026-11-15",
    "week": "第20周·漳州A目标",
    "weekday": "周日",
    "start": "按赛事通知",
    "category": "漳州半马",
    "content": "A目标比赛：前5km稳住，5-15km均匀巡航，15km后根据呼吸、腿感和补给决定是否向2:30推进。",
    "duration": "2小时25分-2小时40分",
    "distance": 21.0975,
    "intensity": "A目标2:30；以当天状态执行",
    "reminder": "这是本周期唯一PB目标；膝踝出现加重疼痛就果断降速或停止。"
  },
  {
    "date": "2026-11-16",
    "week": "第21周·赛后恢复",
    "weekday": "周一",
    "start": "灵活",
    "category": "赛后恢复",
    "content": "完全休息、补水、补碳水，观察膝踝小腿；不跑步。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "赛后24小时以恢复为唯一任务。"
  },
  {
    "date": "2026-11-17",
    "week": "第21周·赛后恢复",
    "weekday": "周二",
    "start": "06:10",
    "category": "恢复走",
    "content": "散步20-30分钟；若下楼仍疼或步态异常，完全休息。",
    "duration": "0-30分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不跑步，不骑行。"
  },
  {
    "date": "2026-11-18",
    "week": "第21周·赛后恢复",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "只做活动度、轻核心和单腿平衡；任何疼痛都停止。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "不练力量到酸。"
  },
  {
    "date": "2026-11-19",
    "week": "第21周·赛后恢复",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑3km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 3,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-11-20",
    "week": "第21周·赛后恢复",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-11-21",
    "week": "第21周·赛后恢复",
    "weekday": "周六",
    "start": "灵活",
    "category": "恢复骑行或步行",
    "content": "轻松骑行20-30km或散步30分钟；全程低强度。",
    "duration": "30-75分钟",
    "distance": 0,
    "intensity": "RPE 2-3",
    "reminder": "不追距离，不爬坡。"
  },
  {
    "date": "2026-11-22",
    "week": "第21周·赛后恢复",
    "weekday": "周日",
    "start": "07:00",
    "category": "恢复跑",
    "content": "轻松跑4km；若跑后关节不适，下一周继续降量。",
    "duration": "30-35分钟",
    "distance": 4,
    "intensity": "非常轻松",
    "reminder": "跑完应像热身，没有训练感。"
  },
  {
    "date": "2026-11-23",
    "week": "第22周·赛后恢复延续",
    "weekday": "周一",
    "start": "灵活",
    "category": "休息",
    "content": "完全休息；可做髋、臀、小腿和脚踝活动度10分钟。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "不补跑，给下一次关键训练留恢复。"
  },
  {
    "date": "2026-11-24",
    "week": "第22周·赛后恢复延续",
    "weekday": "周二",
    "start": "06:10",
    "category": "恢复跑",
    "content": "轻松跑4km；先快走3分钟，跑后做单腿平衡和提踵各2组。",
    "duration": "25-30分钟",
    "distance": 4,
    "intensity": "非常轻松，能聊天",
    "reminder": "膝或踝不适加重就改20分钟快走。"
  },
  {
    "date": "2026-11-25",
    "week": "第22周·赛后恢复延续",
    "weekday": "周三",
    "start": "21:00",
    "category": "力量",
    "content": "15-20分钟：臀桥、提踵、台阶下放、单腿平衡、死虫式，各2组；不做跳跃。",
    "duration": "15-20分钟",
    "distance": 0,
    "intensity": "RPE 4-5",
    "reminder": "动作全程无痛；不练到酸。"
  },
  {
    "date": "2026-11-26",
    "week": "第22周·赛后恢复延续",
    "weekday": "周四",
    "start": "06:10",
    "category": "轻松跑",
    "content": "轻松跑5km；前1km刻意放慢，结束后慢走3分钟。",
    "duration": "25-30分钟",
    "distance": 5,
    "intensity": "能聊天，不卡配速",
    "reminder": "杭州高温高湿时按体感放慢。"
  },
  {
    "date": "2026-11-27",
    "week": "第22周·赛后恢复延续",
    "weekday": "周五",
    "start": "灵活",
    "category": "休息",
    "content": "休息；整理周末装备，做小腿和臀部拉伸。",
    "duration": "0-10分钟",
    "distance": 0,
    "intensity": "无",
    "reminder": "周五不补训练。"
  },
  {
    "date": "2026-11-28",
    "week": "第22周·赛后恢复延续",
    "weekday": "周六",
    "start": "06:30",
    "category": "周六二选一",
    "content": "方案A：低强度骑行25km，全程能聊天、不冲坡；方案B：LSD 8km，前2km刻意放慢。二选一，不叠加。",
    "duration": "骑行约2小时内；LSD按配速完成",
    "distance": 0,
    "intensity": "骑行RPE 3-4 / LSD能聊天",
    "reminder": "仍处赛后恢复期；骑行平路低强度，LSD最多8km。"
  },
  {
    "date": "2026-11-29",
    "week": "第22周·赛后恢复延续",
    "weekday": "周日",
    "start": "07:30",
    "category": "赛后恢复",
    "content": "轻松跑4-6km或散步30分钟；按漳州赛后两周的膝踝反应选择。",
    "duration": "30-50分钟",
    "distance": 4,
    "intensity": "非常轻松",
    "reminder": "原11月29日赛事已取消；今天只做恢复，不测试状态。"
  }
];
